const data = {
  products: [
    {
      _id: '1',
      name: ' Nike ',
      category: 'test0',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'test0',
    },
    {
      _id: '2',
      name: ' Adidas ',
      category: 'test1',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'test1',
    },
    {
      _id: '3',
      name: ' test2',
      category: 'test',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'test2',
    },
    {
      _id: '4',
      name: 'Nike ',
      category: 'test3',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'test3',
    },
    {
      _id: '5',
      name: 'Puma ',
      category: 'test4',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'test4',
    },
    {
      _id: '6',
      name: 'Adidas ',
      category: 'test5',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'test5',
    },
  ],
};
export default data;
